#ifndef _MESSAGE_DEFINE_H_
#define _MESSAGE_DEFINE_H_

enum MessageType
{
	MESSAGE_INVALID,
	MESSAGE_C_GH_LOGIN,
	MESSAGE_C_GH_CHAT,
	MESSAGE_S_SVR_LOGIN_RESULT,
	MESSAGE_S_SVR_CHAT,
	MESSAGE_NUM,
};

#endif